#!/bin/bash

echo "Waring: It's not support other OS: like Centos."
echo "Press any key to continue..."
read tmp
sudo mkdir -p /usr/share/fonts/my_fonts
sudo cp user_fonts/YaHei\ Consolas\ Hybrid.ttf /usr/share/fonts/my_fonts
sudo cd /usr/share/fonts/my_fonts
sudo mkfontscale
sudo mkfontsdir
